### PR TITLE
fix: rename `InternalAnchor`/`ExternalAnchor` prop types

### PR DESCRIPTION
**Pull request by astorije**
## PR Checklist

- [x] Addresses an existing open issue: not quite an issue, but this was discussed [here](https://github.com/SquiggleTools/boston-ts-website/pull/284#discussion_r1656539369)
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/boston-ts-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/boston-ts-website/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This was identified as a typo in https://github.com/SquiggleTools/boston-ts-website/pull/284#discussion_r1656539369

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Looks great to me, thanks!

**Comment by astorije** [comment]
@JoshuaKGoldberg do I need to do anything about this GitHub check?

**Comment by JoshuaKGoldberg** [comment]
Nope :)

**Comment by JoshuaKGoldberg** [comment]
Nope :) it's complaining about the lack of `fixes #...` but failing to report that because of https://github.com/mtfoley/pr-compliance-action/issues/368.

**Pull request merged**
