### PR TITLE
feat: add Xavier Ruiz to `/about` page

### PR DESCRIPTION
**Pull request by xav-ie**
## PR Checklist

- [x] Addresses an existing open issue: fixes nothing
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/boston-ts-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/boston-ts-website/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Yay! I am now officially an organizer of Boston TS Club!

🐢

### CODE REVIEW

**Review by astorije — APPROVED** [review]
🎉🎉🎉

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @astorije for maintenance.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @xav-ie for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by JoshuaKGoldberg** [comment]
https://github.com/all-contributors please add @astorije for maintenance.

**Comment by JoshuaKGoldberg** [comment]
https://github.com/all-contributors please add @xav-ie for code.

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @astorije for maintenance.

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @xav-ie for code.

**Pull request merged**
